### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by dkanafeev** [dkanafeev/data-collector-road-defects#1]
should be done by 04/17
Мне лень писать на англ. Возможно еще что-то потом добавлю
- [x] Переехать обратно на тестовый пример Hello, Cordova! (Дамир)
- [x] Добавить все доступные датчики - гироскоп, компас и т.д. (Дамир, зависит от п.1)
- [x] Запись в файл починить (Дамир)
- [x] Время опроса датчиков сократить до минимально возможного (~25-50ms) 
  (уже сделано для акселерометра, остальные добавит Даша)
- [x] Сделать отдельные файлы для каждого из датчиков. Формат: данные-время 
  (просто добавить вызовы writeToFile, уже сделано для акселерометра, остальные добавит Даша)
- [x] Добавить вывод времени с точностью до ms (Даша)

Удалено:
- Добавить запись видео - внешний источник
