### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by dkanafeev** [dkanafeev/data-collector-road-defects#2]
should be done by 05/22
- [ ] Отображение местоположения на карте по GPS
- [ ] Отправка данных на сервер
- [ ] Отображение дефектов на карте
- [ ] Отображение местоположения расчитанного
